<?php /** @var \Dintero\Checkout\Block\ProductPagePaymentLink $block */ ?>

<div class="dintero-button-container centered-button">

    <div class="dintero-button-container__cell">
        <a href="javascript:;"
           class="dintero-addToCart"
           id="dintero-addToCart-<?= /* @noEscape */ $block->getJsId() ?>"
           data-mage-init='{"dinteroProductAdd": {"checkoutUrl": "<?= $block->escapeUrl($block->getExpressCheckoutUrl()); ?>"}}'>
            <img src="<?= $block->getViewFileUrl('Dintero_Checkout::images/checkout-express-dark-round.svg'); ?>" />
        </a>
    </div>
</div>
