<?php

use Dintero\Checkout\Model\Dintero;

/**
 * @var \Dintero\Checkout\Block\Adminhtml\Order\PaymentInfo $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->getPaymentInfo() && $block->getPaymentInfo()->getMethod() === Dintero::METHOD_CODE): ?>
<table class="admin__table-secondary order-information-table stripe payment-info">
    <tbody>
        <?php if ($this->getPaymentInfo()->getLastTransId()): ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Payment')); //phpcs:ignore ?></th>
            <td class="dintero-link">
                <a href="<?= $escaper->escapeUrl($block->getTransactionUrl()) ?>" target="_blank">
                    <?= $escaper->escapeHtml(__('View Payment Details')) ?>
                </a>
            </td>
        </tr>
        <?php endif; ?>
        <tr>
            <th><?= $escaper->escapeHtml(__('Payment status')); //phpcs:ignore ?></th>
            <td class="dintero-payment-status">
                <?= $escaper->escapeHtml($block->getPaymentStatus()); ?>
            </td>
        </tr>
    </tbody>
</table>
<?php endif; ?>
